// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fctxecelnxemxyctjcry.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZjdHhlY2VsbnhlbXh5Y3RqY3J5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc5NzM5MzEsImV4cCI6MjA1MzU0OTkzMX0.Xl1L5J40AowALsSu9FcnXyNe6_HlNxqwMHzWVK2ivsA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);